language: go

go:
    - 1.6.3
    - tip

install:
    - go get github.com/pkg/errors
    - go get github.com/pkg/term
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v ./...
    - go test -covermode=count -coverprofile=coverage.out ./vm
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
