language: go

go:
    - 1.6.3
      env: REPORT_COVERAGE=true
    - tip
      env: REPORT_COVERAGE=false

install:
    - go get github.com/pkg/errors
    - go get github.com/pkg/term
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script: make
