language: go

matrix:
    include:
        - go: 1.4
          os: linux
          env: REPORT_COVERAGE=false
        - go: 1.7
          os: linux
          env: REPORT_COVERAGE=true
        - go: tip
          os: linux
          env: REPORT_COVERAGE=false
    fast_finish: true
    allow_failures:
        - go: tip

install:
    - go get github.com/pkg/errors
    - go get github.com/pkg/term
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script: make
